In [ ]:
import torch

In [ ]:
x = torch.tensor(87)
x.ndim

0

In [ ]:
x = torch.tensor([1, 2, 3])
x.ndim

1

In [ ]:
x = torch.tensor([[1, 2, 3],
          [4, 5, 6]])
x.shape

torch.Size([2, 3])

In [ ]:
torch.manual_seed(87)
x = torch.arange(2, 3, 4)
x

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [ ]:
x = torch.arange(0, 11, 2)
x

tensor([ 0,  2,  4,  6,  8, 10])

In [ ]:
torch.tensor([1, 2, 3],
      dtype=torch.float64,
             device=None,
             requires_grad=False)

In [15]:
x = torch.tensor([[[0.1, 0.2, 0.3],
           [0.4, 0.5, 0.6]]])
x[0][0][0], x.dtype

(tensor(0.1000), torch.float32)

In [16]:
x = torch.tensor([[0.1, 0.2, 0.3],
          [0.4, 0.5, 0.6]])

x / 10

tensor([[0.0100, 0.0200, 0.0300],
        [0.0400, 0.0500, 0.0600]])

In [18]:
x = torch.tensor([[0.1, 0.2, 0.3],
          [0.4, 0.5, 0.6]])

y = torch.tensor([[1, 2, 3],
          [4, 5, 6]])

x / y

tensor([[0.1000, 0.1000, 0.1000],
        [0.1000, 0.1000, 0.1000]])

In [19]:
x = torch.tensor([[1, 2],
          [3, 4],
          [5, 6]])

y = torch.tensor([[1, 2, 3],
          [4, 5, 6]])

torch.matmul(x, y)

tensor([[ 9, 12, 15],
        [19, 26, 33],
        [29, 40, 51]])

In [20]:
x = torch.tensor([[1, 2],
          [3, 4],
          [5, 6]])

x.T

tensor([[1, 3, 5],
        [2, 4, 6]])

In [21]:
x = torch.arange(0, 10)
x.reshape(2,5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [22]:
import numpy as np

array = np.array([1, 2, 3])
tensor = torch.from_numpy(array)
array, tensor

(array([1, 2, 3]), tensor([1, 2, 3]))

In [23]:
tensor = torch.tensor([1, 2, 3])
array = tensor.numpy()
tensor, array

(tensor([1, 2, 3]), array([1, 2, 3]))